# config.yml - 配置 VoidTrialChambersPlugin

# 隨機座標生成範圍 (X, Z)，預設 500
trial_range: 500

# 試煉房間生成的固定 Y 座標，預設 50
trial_chamber:
  y: 50

# 死亡時不觸發插件內傳送的世界列表
excluded_worlds:
  - world
  - world_nether
  - world_the_end
