name: VoidTrialChambersPlugin
version: 1.1-SNAPSHOT
main: org.swim.voidTrialChambersPlugin.VoidTrialChambersPlugin
api-version: '1.21.4'
description: A plugin that allows players to enter Trial Chambers in a void world
commands:
  trialchambers:
    description: Enter a Trial Chamber in a void world
    usage: /trialchambers
    permission: trialchambers.use
    permission-message: You don't have permission to use this command.

  exittrial:
    description: "退出試煉，傳送回主世界重生點"
    usage: /exittrial

  trialleaderboard:
    description: 查看試煉副本排行榜
    usage: /<command> [solo|team|kills] [EASY|NORMAL|HELL]

  trailteam:
    description: 試煉副本邀請系統

permissions:
  trialchambers.use:
    description: Allows player to use the /trialchambers command
    default: true
